name: water_service
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  bcrypt: ^1.1.3
  
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  qr_flutter: ^4.0.0
  printing: ^5.3.9
  mobile_scanner: ^2.1.0
  path_provider: ^2.0.11
  intl: ^0.18.0
  qrscan: ^0.3.3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
